### ISSUE TITLE
Configuration for external access

### ISSUE THREAD

**Issue by seb2point0** [jonohill/docker-openvpn-proxy#3]
Does this image allow external access from WAN? What configuration would that require?

**Comment by jonohill** [comment]
Yes I expect that'd work but it's not something I've tried. From a security perspective I wouldn't recommend exposing over WAN without proxy TLS and authentication, which this image does not implement.
If you want the PAC script to work you'd need to set `OPENVPN_HOST` to the WAN host name, beyond that I don't think there'd be any special config required.

**Comment by joeblowout** [comment]
Sir, it's still not working for external IP access no matter what I try. I intend to setup a middle man server on my vps for my VPN subscription, where all traffic is routed through said VPS. Seems like this openvpn docker only accepts localhost address, as tested on qbittorrent docker container http proxy setting. So long the http proxy addresses reference localhost(127.0.0.1, 0.0.0.0, localhost), it will work, but not others
